<?php

namespace ShopBundle\Repository;

/**
 * LivRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivRepository extends \Doctrine\ORM\EntityRepository
{
}
