<?php

namespace fournisseurBundle\Repository;

/**
 * categorieFRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categorieFRepository extends \Doctrine\ORM\EntityRepository
{
}
