liv_index:
    path:     /
    defaults: { _controller: "ShopBundle:Liv:index" }
    methods:  GET

liv_show:
    path:     /{id}/show
    defaults: { _controller: "ShopBundle:Liv:show" }
    methods:  GET

liv_new:
    path:     /new
    defaults: { _controller: "ShopBundle:Liv:new" }
    methods:  [GET, POST]

liv_edit:
    path:     /{id}/edit
    defaults: { _controller: "ShopBundle:Liv:edit" }
    methods:  [GET, POST]

liv_delete:
    path:     /{id}/delete
    defaults: { _controller: "ShopBundle:Liv:delete" }
    methods:  DELETE
