<?php

namespace ShopBundle\Repository;

/**
 * VehRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehRepository extends \Doctrine\ORM\EntityRepository
{
    public function  editCurrentAdQB(){

        $query=$this->getEntityManager()
            ->createQuery("UPDATE ShopBundle:Veh v SET v.status=:stat WHERE CURRENT_DATE() BETWEEN v.debutcontrat AND v.fincontrat")
            ->setParameter(':stat','Fonctionnement')
            ->execute();

    }
    public function  editHistoryAdQB(){

        $query=$this->getEntityManager()
            ->createQuery("UPDATE ShopBundle:Veh v SET v.status=:stat WHERE CURRENT_DATE() > v.fincontrat")
            ->setParameter(':stat','FinFonctionnement')
            ->execute();

    }
    public function  editProgAdQB(){

        $query=$this->getEntityManager()
            ->createQuery("UPDATE ShopBundle:Veh v SET v.status=:stat WHERE CURRENT_DATE() < v.debutcontrat")
            ->setParameter(':stat','Programmepourfonctionnement')
            ->execute();

    }
}
